version: "3.3"
services:
    db:
        image: mysql:5.7
        container_name: easyappointments_database
        hostname: easyappointments_db
        #volumes:
        #    - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=easyappointments
        ports:
            - "8001:3306"
    app:
        image: local/easyappointments:local
        container_name: easyappointments-server
        environment: 
                BASE_URL : "http://localhost:8080"
                LANGUAGE: "english"
                DEBUG_MODE: 'true'
                DB_HOST: easyappointments_db
                DB_NAME: easyappointments
                DB_USERNAME: root
                DB_PASSWORD: password
                GOOGLE_SYNC_FEATURE: 'false'
                GOOGLE_PRODUCT_NAME: 'xx'
                GOOGLE_CLIENT_ID: 'xx'
                GOOGLE_CLIENT_SECRET: 'xx'
                GOOGLE_API_KEY: 'xx'
        ports:
            - "8080:8080"
       # volumes:
       #     - ../:/var/www/html
       #     - ./server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
